### ISSUE TITLE
iam_user_no_policies_check does not cover all scenarios

### ISSUE THREAD

**Issue by mlevit** [servian/aws-auto-remediate#27]
As it currently stands the newly implemented pull request #26 for `iam_user_no_policies_check` remediation only removes IAM **managed** policies attached to the user however users can also have inline policies.

The current paginator used `list_attached_user_policies` will not capture inline policies which can only be captured using `list_user_policies` and deleted using `delete_user_policy`.

**Comment by jihygk** [comment]
This depends on the interpretation of `iam-user-no-policies-check`, which says "Checks that none of your IAM users have policies attached". [The terminology used within the AWS documentation and API imply "attach/detach -> managed policies" and "embed/delete -> inline policies".](https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_manage-attach-detach.html#attach-detach-etc-terminology)

I don't think having inline user policies trigger `iam-user-no-policies-check`, as they have a valid use case such as maintaining a (strict) 1:1 relationship between entity and policy (see [Using Inline Policies](https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_managed-vs-inline.html#choosing-managed-or-inline) section).
