### ISSUE TITLE
More permissive license

### ISSUE THREAD

**Issue by iann0036** [servian/aws-auto-remediate#42]
Hi,

What are the chances of moving the project to a more permissive license structure like MIT? The current license is incompatible for use with some...let's say more "restrictive" organisations.

Thanks for your consideration,
Ian.

**Comment by mlevit** [comment]
Hey @iann0036. Happy to consider, could you let me know what part of the GPL license are you finding restrictive?

Our main reasoning behind GPL was to encourage contribution back in.

**Comment by iann0036** [comment]
Unfortunately, literally the part that encourages contributions back 👎

Some businesses may need to make changes (custom rulesets or remediations) which would reveal inner business practices.

**Comment by mlevit** [comment]
[According to this discussion on StackOverflow](https://stackoverflow.com/a/11752204/149166)

> You don't have to open-source your changes if you're using GPL. You could modify it and use it for your own purpose as long as you're not distributing it. BUT... if you DO distribute it, then your entire project that is using the GPL code also becomes GPL automatically.

**Comment by iann0036** [comment]
Yep. I think that's the big issue for the businesses, they're scared of the implications there.

Completely fine if you keep it as is, just a suggestion is all.
